postgresql:
    host: "localhost"
    port: "5432"
    database: "postgres"
    username: "postgresuser"
    password: "postgrespassword"
    sslmode: "disable"
redis:
    address: "localhost:6379"
    password: "12345"
    database: 0